"""Normalized schemas for all supported financial document types."""

from __future__ import annotations

from pbc_chaos.core.types import DocumentType
from pbc_chaos.schemas.base import DocumentSchema, SchemaRelationship, nf
from pbc_chaos.schemas.base import FieldRequirement as Req
from pbc_chaos.schemas.base import FieldType as Type
from pbc_chaos.schemas.common import COMMON_DOCUMENT_FIELDS, REMARKS


def rel(
    name: str,
    target: DocumentType,
    description: str,
    *,
    join_fields: tuple[tuple[str, str], ...] = (),
    tolerance: str | None = None,
) -> SchemaRelationship:
    return SchemaRelationship(
        name=name,
        target_document_type=target,
        description=description,
        join_fields=join_fields,
        tolerance=tolerance,
    )


PBC_REQUEST_LIST_SCHEMA = DocumentSchema(
    document_type=DocumentType.PBC_REQUEST_LIST,
    display_name="PBC Request List",
    grain="One audit support request tracked by the client or audit team.",
    primary_key=("client_id", "financial_year", "request_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf(
            "request_number",
            Type.INTEGER,
            Req.RECOMMENDED,
            "Visible row number used in the request tracker.",
            aliases=("No.", "No", "Line"),
        ),
        nf(
            "request_id",
            Type.IDENTIFIER,
            Req.REQUIRED,
            "PBC request identifier.",
            aliases=("Request ID", "Req ID", "Ref"),
            nullable=False,
        ),
        nf(
            "request_description",
            Type.STRING,
            Req.REQUIRED,
            "Support requested from the client.",
            aliases=("Request / Description", "Request", "Description"),
            nullable=False,
        ),
        nf(
            "detail_remark",
            Type.STRING,
            Req.OPTIONAL,
            "Detailed remark or scope qualifier for the request.",
            aliases=("Details / Remark", "Details", "Remark"),
        ),
        nf("purpose", Type.STRING, Req.RECOMMENDED, "Audit purpose or assertion covered."),
        nf(
            "period_label",
            Type.STRING,
            Req.RECOMMENDED,
            "Human-readable period requested, such as FY2024 or Dec 2024.",
            aliases=("Period",),
        ),
        nf(
            "file_type_requested",
            Type.STRING,
            Req.RECOMMENDED,
            "Requested support format.",
            aliases=("Format / File Type", "File Type", "Format"),
        ),
        nf(
            "owner_pic",
            Type.STRING,
            Req.RECOMMENDED,
            "Client owner or person in charge.",
            aliases=("Owner (PIC)", "PIC", "Owner"),
        ),
        nf("due_date", Type.DATE, Req.RECOMMENDED, "Requested submission due date."),
        nf(
            "status",
            Type.ENUM,
            Req.RECOMMENDED,
            "Client submission status.",
            allowed_values=(
                "not_started",
                "in_progress",
                "partial",
                "received",
                "done",
                "not_applicable",
            ),
        ),
        nf("date_received", Type.DATE, Req.OPTIONAL, "Date the support was received."),
        nf(
            "review_status",
            Type.STRING,
            Req.OPTIONAL,
            "Audit team review status.",
            aliases=("Review Status",),
        ),
        nf(
            "auditor_comment",
            Type.STRING,
            Req.OPTIONAL,
            "Visible auditor or finance-team comment.",
            aliases=("Auditor Comment", "Comment"),
        ),
        nf(
            "follow_up_required",
            Type.BOOLEAN,
            Req.RECOMMENDED,
            "Whether follow-up is required.",
            aliases=("Follow Up??", "Follow Up", "Reminder"),
        ),
        nf(
            "update_flag",
            Type.BOOLEAN,
            Req.OPTIONAL,
            "Whether the row is new or updated in the latest tracker version.",
            aliases=("Updated", "New / Updated"),
        ),
        REMARKS,
    ),
    relationships=(
        rel(
            "request_list_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "Trial balance requests should correspond to the generated trial balance sheet.",
        ),
        rel(
            "request_list_to_general_ledger",
            DocumentType.GENERAL_LEDGER,
            "GL requests should correspond to the generated general ledger sheet.",
        ),
    ),
    quality_rules=(
        "Each request should have a stable request_id before tracker chaos.",
        "Status and follow-up fields may be intentionally inconsistent after chaos.",
    ),
)


TRIAL_BALANCE_SCHEMA = DocumentSchema(
    document_type=DocumentType.TRIAL_BALANCE,
    display_name="Trial Balance",
    grain="One account balance per client, financial year, period end, and account code.",
    primary_key=("client_id", "financial_year", "period_end", "account_code"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf(
            "account_code",
            Type.STRING,
            Req.REQUIRED,
            "General ledger account code.",
            concept="account",
            aliases=("GL", "Ledger", "Acc Code", "A/C", "Account Number", "GL No"),
            nullable=False,
        ),
        nf(
            "account_name",
            Type.STRING,
            Req.REQUIRED,
            "General ledger account name.",
            concept="account",
            aliases=("Account", "Description", "Account Description"),
            nullable=False,
        ),
        nf(
            "account_category",
            Type.ENUM,
            Req.RECOMMENDED,
            "Financial statement category.",
            concept="account",
            allowed_values=("asset", "liability", "equity", "revenue", "expense"),
        ),
        nf(
            "normal_balance",
            Type.ENUM,
            Req.RECOMMENDED,
            "Expected natural balance direction for the account.",
            concept="account",
            allowed_values=("debit", "credit"),
        ),
        nf("opening_debit", Type.DECIMAL, Req.OPTIONAL, "Opening debit balance."),
        nf("opening_credit", Type.DECIMAL, Req.OPTIONAL, "Opening credit balance."),
        nf("period_debit", Type.DECIMAL, Req.RECOMMENDED, "Current period debit movement."),
        nf("period_credit", Type.DECIMAL, Req.RECOMMENDED, "Current period credit movement."),
        nf("closing_debit", Type.DECIMAL, Req.OPTIONAL, "Closing debit balance."),
        nf("closing_credit", Type.DECIMAL, Req.OPTIONAL, "Closing credit balance."),
        nf(
            "closing_balance",
            Type.DECIMAL,
            Req.REQUIRED,
            "Signed closing balance where debit is positive and credit is negative.",
            aliases=("Amount", "Amt", "RM", "Value", "Bal", "Closing Balance"),
            nullable=False,
        ),
        nf("comparative_balance", Type.DECIMAL, Req.OPTIONAL, "Prior year comparative balance."),
        nf("adjustment_amount", Type.DECIMAL, Req.OPTIONAL, "Manual or audit adjustment amount."),
        nf("final_balance", Type.DECIMAL, Req.DERIVED, "Closing balance after adjustments."),
        REMARKS,
    ),
    relationships=(
        rel(
            "tb_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Period movements should roughly equal GL debits and credits grouped by account.",
            join_fields=(("account_code", "account_code"),),
            tolerance="Configured trial_balance_gl_difference_pct.",
        ),
        rel(
            "tb_to_cash_flow",
            DocumentType.CASH_FLOW_SUMMARY,
            "Cash and profit movements can be used to derive cash flow sections.",
            tolerance="Controlled by cash-flow generator assumptions.",
        ),
    ),
    quality_rules=(
        "Sum of closing balances should be near zero before configured chaos.",
        "At least one of closing_balance or debit/credit closing columns must be populated.",
    ),
)

GENERAL_LEDGER_SCHEMA = DocumentSchema(
    document_type=DocumentType.GENERAL_LEDGER,
    display_name="General Ledger",
    grain="One posted accounting transaction line.",
    primary_key=("client_id", "financial_year", "entry_id", "line_number"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("entry_id", Type.IDENTIFIER, Req.REQUIRED, "Stable ledger line identifier.", nullable=False),
        nf("journal_id", Type.IDENTIFIER, Req.RECOMMENDED, "Journal or voucher identifier."),
        nf("line_number", Type.INTEGER, Req.REQUIRED, "Line number within the journal.", nullable=False),
        nf("posting_date", Type.DATE, Req.REQUIRED, "Date posted to the ledger.", nullable=False),
        nf("document_date", Type.DATE, Req.OPTIONAL, "Underlying document or invoice date."),
        nf("period", Type.STRING, Req.RECOMMENDED, "Accounting period label."),
        nf("account_code", Type.STRING, Req.REQUIRED, "GL account code.", concept="account", nullable=False),
        nf("account_name", Type.STRING, Req.RECOMMENDED, "GL account name.", concept="account"),
        nf("account_category", Type.ENUM, Req.OPTIONAL, "Financial statement category."),
        nf("debit", Type.DECIMAL, Req.RECOMMENDED, "Debit amount."),
        nf("credit", Type.DECIMAL, Req.RECOMMENDED, "Credit amount."),
        nf("amount_signed", Type.DECIMAL, Req.REQUIRED, "Signed line amount.", nullable=False),
        nf("counterparty_id", Type.IDENTIFIER, Req.OPTIONAL, "Customer, supplier, employee, or agent ID."),
        nf("counterparty_name", Type.STRING, Req.OPTIONAL, "Counterparty name."),
        nf(
            "counterparty_type",
            Type.ENUM,
            Req.OPTIONAL,
            "Counterparty type.",
            allowed_values=("customer", "supplier", "employee", "agent", "bank", "tax_authority", "other"),
        ),
        nf("source_module", Type.STRING, Req.RECOMMENDED, "ERP module or manual source."),
        nf("document_number", Type.STRING, Req.OPTIONAL, "Invoice, receipt, or source document number."),
        nf("reference", Type.STRING, Req.OPTIONAL, "Reference, cheque number, or voucher number."),
        nf("description", Type.STRING, Req.RECOMMENDED, "Transaction description."),
        nf("cost_center", Type.STRING, Req.OPTIONAL, "Cost center."),
        nf("department", Type.STRING, Req.OPTIONAL, "Department."),
        nf("project_code", Type.STRING, Req.OPTIONAL, "Project or job code."),
        nf("tax_code", Type.STRING, Req.OPTIONAL, "Tax code."),
        nf("created_by", Type.STRING, Req.OPTIONAL, "User who created the entry."),
        nf("posted_by", Type.STRING, Req.OPTIONAL, "User who posted the entry."),
        nf("batch_id", Type.IDENTIFIER, Req.OPTIONAL, "ERP import or posting batch ID."),
        nf("reversal_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether the line reverses another entry."),
        REMARKS,
    ),
    relationships=(
        rel(
            "gl_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "GL grouped by account should tie to trial balance movements.",
            join_fields=(("account_code", "account_code"),),
            tolerance="Configured trial_balance_gl_difference_pct.",
        ),
        rel(
            "gl_to_journal_entry_listing",
            DocumentType.JOURNAL_ENTRY_LISTING,
            "Journal entry listing should be a filtered or annotated view of GL lines.",
            join_fields=(("journal_id", "journal_id"), ("line_number", "line_number")),
        ),
    ),
    quality_rules=(
        "Each journal should have debits equal credits before discrepancy injection.",
        "Debit and credit should not both be populated with positive amounts on the same line.",
    ),
)

AP_AGING_SCHEMA = DocumentSchema(
    document_type=DocumentType.AP_AGING,
    display_name="AP Aging",
    grain="One supplier payable open item at the aging date.",
    primary_key=("client_id", "financial_year", "period_end", "vendor_id", "invoice_number"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("vendor_id", Type.IDENTIFIER, Req.REQUIRED, "Supplier identifier.", nullable=False),
        nf("vendor_name", Type.STRING, Req.REQUIRED, "Supplier name.", aliases=("Supplier", "Vendor"), nullable=False),
        nf("invoice_number", Type.STRING, Req.REQUIRED, "Supplier invoice number.", nullable=False),
        nf("invoice_date", Type.DATE, Req.RECOMMENDED, "Supplier invoice date."),
        nf("due_date", Type.DATE, Req.RECOMMENDED, "Payment due date."),
        nf("aging_date", Type.DATE, Req.REQUIRED, "Date used for aging calculation.", nullable=False),
        nf("days_past_due", Type.INTEGER, Req.DERIVED, "Days past due at aging date."),
        nf(
            "aging_bucket",
            Type.ENUM,
            Req.RECOMMENDED,
            "Normalized aging bucket.",
            allowed_values=("current", "1_30", "31_60", "61_90", "over_90", "unknown"),
        ),
        nf("original_amount", Type.DECIMAL, Req.RECOMMENDED, "Original invoice amount."),
        nf("outstanding_amount", Type.DECIMAL, Req.REQUIRED, "Outstanding payable amount.", nullable=False),
        nf("current_amount", Type.DECIMAL, Req.OPTIONAL, "Current bucket amount."),
        nf("bucket_1_30", Type.DECIMAL, Req.OPTIONAL, "1 to 30 days past due amount."),
        nf("bucket_31_60", Type.DECIMAL, Req.OPTIONAL, "31 to 60 days past due amount."),
        nf("bucket_61_90", Type.DECIMAL, Req.OPTIONAL, "61 to 90 days past due amount."),
        nf("bucket_over_90", Type.DECIMAL, Req.OPTIONAL, "Over 90 days past due amount."),
        nf("payment_terms", Type.STRING, Req.OPTIONAL, "Supplier payment terms."),
        nf("purchase_order_number", Type.STRING, Req.OPTIONAL, "Related purchase order."),
        nf("hold_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether payment is on hold."),
        nf("disputed_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether the payable is disputed."),
        REMARKS,
    ),
    relationships=(
        rel(
            "ap_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "AP aging total should roughly tie to AP control account balance.",
            tolerance="Configured relationship discrepancy mode.",
        ),
        rel(
            "ap_to_supplier_confirmations",
            DocumentType.SUPPLIER_CONFIRMATION_LIST,
            "Supplier confirmation balances should sample or summarize AP aging balances.",
            join_fields=(("vendor_id", "vendor_id"),),
        ),
    ),
)

AR_AGING_SCHEMA = DocumentSchema(
    document_type=DocumentType.AR_AGING,
    display_name="AR Aging",
    grain="One customer receivable open item at the aging date.",
    primary_key=("client_id", "financial_year", "period_end", "customer_id", "invoice_number"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("customer_id", Type.IDENTIFIER, Req.REQUIRED, "Customer identifier.", nullable=False),
        nf("customer_name", Type.STRING, Req.REQUIRED, "Customer name.", aliases=("Debtor", "Customer"), nullable=False),
        nf("invoice_number", Type.STRING, Req.REQUIRED, "Customer invoice number.", nullable=False),
        nf("invoice_date", Type.DATE, Req.RECOMMENDED, "Customer invoice date."),
        nf("due_date", Type.DATE, Req.RECOMMENDED, "Collection due date."),
        nf("aging_date", Type.DATE, Req.REQUIRED, "Date used for aging calculation.", nullable=False),
        nf("days_past_due", Type.INTEGER, Req.DERIVED, "Days past due at aging date."),
        nf(
            "aging_bucket",
            Type.ENUM,
            Req.RECOMMENDED,
            "Normalized aging bucket.",
            allowed_values=("current", "1_30", "31_60", "61_90", "over_90", "unknown"),
        ),
        nf("original_amount", Type.DECIMAL, Req.RECOMMENDED, "Original invoice amount."),
        nf("outstanding_amount", Type.DECIMAL, Req.REQUIRED, "Outstanding receivable amount.", nullable=False),
        nf("current_amount", Type.DECIMAL, Req.OPTIONAL, "Current bucket amount."),
        nf("bucket_1_30", Type.DECIMAL, Req.OPTIONAL, "1 to 30 days past due amount."),
        nf("bucket_31_60", Type.DECIMAL, Req.OPTIONAL, "31 to 60 days past due amount."),
        nf("bucket_61_90", Type.DECIMAL, Req.OPTIONAL, "61 to 90 days past due amount."),
        nf("bucket_over_90", Type.DECIMAL, Req.OPTIONAL, "Over 90 days past due amount."),
        nf("credit_terms", Type.STRING, Req.OPTIONAL, "Customer credit terms."),
        nf("salesperson", Type.STRING, Req.OPTIONAL, "Responsible salesperson."),
        nf("collection_status", Type.STRING, Req.OPTIONAL, "Collection or follow-up status."),
        nf("disputed_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether the receivable is disputed."),
        REMARKS,
    ),
    relationships=(
        rel(
            "ar_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "AR aging total should roughly tie to AR control account balance.",
            tolerance="Configured relationship discrepancy mode.",
        ),
        rel(
            "ar_to_customer_confirmations",
            DocumentType.CUSTOMER_CONFIRMATION_LIST,
            "Customer confirmation balances should sample or summarize AR aging balances.",
            join_fields=(("customer_id", "customer_id"),),
        ),
    ),
)

BANK_RECONCILIATION_SCHEMA = DocumentSchema(
    document_type=DocumentType.BANK_RECONCILIATION,
    display_name="Bank Reconciliation",
    grain="One bank reconciliation summary or reconciling item line.",
    primary_key=("client_id", "financial_year", "period_end", "bank_account_id", "recon_item_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("bank_account_id", Type.IDENTIFIER, Req.REQUIRED, "Bank account identifier.", nullable=False),
        nf("bank_name", Type.STRING, Req.RECOMMENDED, "Bank name."),
        nf("bank_account_number", Type.STRING, Req.RECOMMENDED, "Masked or fake bank account number."),
        nf("recon_item_id", Type.IDENTIFIER, Req.REQUIRED, "Reconciliation item identifier.", nullable=False),
        nf(
            "recon_item_type",
            Type.ENUM,
            Req.REQUIRED,
            "Type of reconciliation item.",
            allowed_values=(
                "statement_balance",
                "book_balance",
                "deposit_in_transit",
                "outstanding_cheque",
                "bank_charge",
                "interest",
                "adjustment",
                "unreconciled",
            ),
            nullable=False,
        ),
        nf("transaction_date", Type.DATE, Req.OPTIONAL, "Transaction date for reconciling item."),
        nf("reference", Type.STRING, Req.OPTIONAL, "Cheque, receipt, or bank reference."),
        nf("description", Type.STRING, Req.RECOMMENDED, "Reconciliation line description."),
        nf("bank_amount", Type.DECIMAL, Req.OPTIONAL, "Amount per bank statement."),
        nf("book_amount", Type.DECIMAL, Req.OPTIONAL, "Amount per cash book or GL."),
        nf("difference_amount", Type.DECIMAL, Req.DERIVED, "Difference between bank and book amount."),
        nf("statement_balance", Type.DECIMAL, Req.OPTIONAL, "Closing balance per bank statement."),
        nf("book_balance", Type.DECIMAL, Req.OPTIONAL, "Closing cash balance per book."),
        nf("adjusted_bank_balance", Type.DECIMAL, Req.OPTIONAL, "Bank balance after reconciling items."),
        nf("adjusted_book_balance", Type.DECIMAL, Req.OPTIONAL, "Book balance after reconciling items."),
        nf("variance", Type.DECIMAL, Req.DERIVED, "Residual unreconciled difference."),
        nf("cleared_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether the item has cleared."),
        nf("matched_gl_entry_id", Type.IDENTIFIER, Req.OPTIONAL, "Matched GL entry identifier."),
        nf("matched_bank_reference", Type.STRING, Req.OPTIONAL, "Matched bank statement reference."),
        REMARKS,
    ),
    relationships=(
        rel(
            "bank_recon_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Book balance should roughly tie to GL cash account.",
            join_fields=(("matched_gl_entry_id", "entry_id"),),
            tolerance="Configured bank reconciliation difference amount.",
        ),
    ),
)

PAYROLL_SUMMARY_SCHEMA = DocumentSchema(
    document_type=DocumentType.PAYROLL_SUMMARY,
    display_name="Payroll Summary",
    grain="One payroll run summary by department or pay group.",
    primary_key=("client_id", "financial_year", "pay_run_id", "department"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("pay_run_id", Type.IDENTIFIER, Req.REQUIRED, "Payroll run identifier.", nullable=False),
        nf("pay_period_start", Type.DATE, Req.REQUIRED, "Payroll period start date.", nullable=False),
        nf("pay_period_end", Type.DATE, Req.REQUIRED, "Payroll period end date.", nullable=False),
        nf("payment_date", Type.DATE, Req.RECOMMENDED, "Payroll payment date."),
        nf("department", Type.STRING, Req.REQUIRED, "Department or pay group.", nullable=False),
        nf("employee_count", Type.INTEGER, Req.RECOMMENDED, "Number of employees in the summary line."),
        nf("basic_salary", Type.DECIMAL, Req.RECOMMENDED, "Basic salary amount."),
        nf("overtime_amount", Type.DECIMAL, Req.OPTIONAL, "Overtime amount."),
        nf("allowance_amount", Type.DECIMAL, Req.OPTIONAL, "Allowance amount."),
        nf("bonus_amount", Type.DECIMAL, Req.OPTIONAL, "Bonus amount."),
        nf("gross_pay", Type.DECIMAL, Req.REQUIRED, "Gross payroll amount.", nullable=False),
        nf("employee_deductions", Type.DECIMAL, Req.RECOMMENDED, "Total employee deductions."),
        nf("employer_contributions", Type.DECIMAL, Req.RECOMMENDED, "Total employer statutory contributions."),
        nf("tax_withheld", Type.DECIMAL, Req.RECOMMENDED, "Payroll tax or PCB withheld."),
        nf("net_pay", Type.DECIMAL, Req.REQUIRED, "Net payroll paid to employees.", nullable=False),
        REMARKS,
    ),
    relationships=(
        rel(
            "payroll_summary_to_detail",
            DocumentType.PAYROLL_DETAIL,
            "Payroll detail should aggregate near payroll summary by pay run and department.",
            join_fields=(("pay_run_id", "pay_run_id"), ("department", "department")),
            tolerance="Configured payroll summary difference pct.",
        ),
        rel(
            "payroll_summary_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Gross pay, deductions, and net pay should map to payroll GL postings.",
            tolerance="Controlled by payroll discrepancy settings.",
        ),
    ),
)

PAYROLL_DETAIL_SCHEMA = DocumentSchema(
    document_type=DocumentType.PAYROLL_DETAIL,
    display_name="Payroll Detail",
    grain="One employee payroll line per pay run.",
    primary_key=("client_id", "financial_year", "pay_run_id", "employee_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("pay_run_id", Type.IDENTIFIER, Req.REQUIRED, "Payroll run identifier.", nullable=False),
        nf("employee_id", Type.IDENTIFIER, Req.REQUIRED, "Employee identifier.", nullable=False),
        nf("employee_name", Type.STRING, Req.REQUIRED, "Employee name.", nullable=False),
        nf("department", Type.STRING, Req.RECOMMENDED, "Employee department."),
        nf("position", Type.STRING, Req.OPTIONAL, "Employee job title."),
        nf("pay_period_start", Type.DATE, Req.REQUIRED, "Payroll period start date.", nullable=False),
        nf("pay_period_end", Type.DATE, Req.REQUIRED, "Payroll period end date.", nullable=False),
        nf("payment_date", Type.DATE, Req.RECOMMENDED, "Payroll payment date."),
        nf("basic_salary", Type.DECIMAL, Req.RECOMMENDED, "Basic salary amount."),
        nf("overtime_amount", Type.DECIMAL, Req.OPTIONAL, "Overtime amount."),
        nf("allowance_amount", Type.DECIMAL, Req.OPTIONAL, "Allowance amount."),
        nf("bonus_amount", Type.DECIMAL, Req.OPTIONAL, "Bonus amount."),
        nf("commission_amount", Type.DECIMAL, Req.OPTIONAL, "Employee commission amount."),
        nf("gross_pay", Type.DECIMAL, Req.REQUIRED, "Gross pay before deductions.", nullable=False),
        nf("epf_employee", Type.DECIMAL, Req.OPTIONAL, "Employee EPF deduction."),
        nf("socso_employee", Type.DECIMAL, Req.OPTIONAL, "Employee SOCSO deduction."),
        nf("eis_employee", Type.DECIMAL, Req.OPTIONAL, "Employee EIS deduction."),
        nf("pcb_tax", Type.DECIMAL, Req.OPTIONAL, "PCB or payroll tax deduction."),
        nf("other_deductions", Type.DECIMAL, Req.OPTIONAL, "Other employee deductions."),
        nf("net_pay", Type.DECIMAL, Req.REQUIRED, "Net pay to employee.", nullable=False),
        nf("epf_employer", Type.DECIMAL, Req.OPTIONAL, "Employer EPF contribution."),
        nf("socso_employer", Type.DECIMAL, Req.OPTIONAL, "Employer SOCSO contribution."),
        nf("eis_employer", Type.DECIMAL, Req.OPTIONAL, "Employer EIS contribution."),
        nf("payment_method", Type.STRING, Req.OPTIONAL, "Payment method."),
        nf("bank_account_masked", Type.STRING, Req.OPTIONAL, "Masked employee bank account."),
        nf("join_date", Type.DATE, Req.OPTIONAL, "Employee join date."),
        nf("termination_date", Type.DATE, Req.OPTIONAL, "Employee termination date."),
        REMARKS,
    ),
    relationships=(
        rel(
            "payroll_detail_to_summary",
            DocumentType.PAYROLL_SUMMARY,
            "Payroll detail should aggregate near payroll summary.",
            join_fields=(("pay_run_id", "pay_run_id"), ("department", "department")),
            tolerance="Configured payroll summary difference pct.",
        ),
    ),
)

FIXED_ASSET_REGISTER_SCHEMA = DocumentSchema(
    document_type=DocumentType.FIXED_ASSET_REGISTER,
    display_name="Fixed Asset Register",
    grain="One fixed asset record at the reporting date.",
    primary_key=("client_id", "financial_year", "period_end", "asset_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("asset_id", Type.IDENTIFIER, Req.REQUIRED, "Asset identifier.", nullable=False),
        nf("asset_class", Type.STRING, Req.RECOMMENDED, "Asset class or category."),
        nf("asset_description", Type.STRING, Req.REQUIRED, "Asset description.", nullable=False),
        nf("acquisition_date", Type.DATE, Req.RECOMMENDED, "Asset acquisition date."),
        nf("in_service_date", Type.DATE, Req.OPTIONAL, "Date asset was placed in service."),
        nf("supplier_name", Type.STRING, Req.OPTIONAL, "Supplier or vendor name."),
        nf("invoice_number", Type.STRING, Req.OPTIONAL, "Acquisition invoice number."),
        nf("location", Type.STRING, Req.OPTIONAL, "Physical asset location."),
        nf("department", Type.STRING, Req.OPTIONAL, "Owning department."),
        nf("cost", Type.DECIMAL, Req.REQUIRED, "Gross asset cost.", nullable=False),
        nf("additions", Type.DECIMAL, Req.OPTIONAL, "Current year additions."),
        nf("disposals", Type.DECIMAL, Req.OPTIONAL, "Current year disposals at cost."),
        nf("depreciation_method", Type.STRING, Req.RECOMMENDED, "Depreciation method."),
        nf("useful_life_months", Type.INTEGER, Req.RECOMMENDED, "Useful life in months."),
        nf("residual_value", Type.DECIMAL, Req.OPTIONAL, "Residual or salvage value."),
        nf("accumulated_depreciation_opening", Type.DECIMAL, Req.OPTIONAL, "Opening accumulated depreciation."),
        nf("depreciation_current_year", Type.DECIMAL, Req.RECOMMENDED, "Current year depreciation."),
        nf("accumulated_depreciation_closing", Type.DECIMAL, Req.RECOMMENDED, "Closing accumulated depreciation."),
        nf("net_book_value", Type.DECIMAL, Req.REQUIRED, "Net book value at period end.", nullable=False),
        nf("disposal_date", Type.DATE, Req.OPTIONAL, "Disposal date, if disposed."),
        nf("disposal_proceeds", Type.DECIMAL, Req.OPTIONAL, "Disposal proceeds."),
        nf("gain_loss_on_disposal", Type.DECIMAL, Req.DERIVED, "Gain or loss on disposal."),
        nf("status", Type.ENUM, Req.RECOMMENDED, "Asset status.", allowed_values=("active", "disposed", "fully_depreciated")),
        REMARKS,
    ),
    relationships=(
        rel(
            "far_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "Cost, accumulated depreciation, and depreciation expense should tie to PPE accounts.",
            tolerance="Controlled by discrepancy settings.",
        ),
    ),
)

INVENTORY_LISTING_SCHEMA = DocumentSchema(
    document_type=DocumentType.INVENTORY_LISTING,
    display_name="Inventory Listing",
    grain="One inventory item, location, and lot/serial balance at the count date.",
    primary_key=("client_id", "financial_year", "period_end", "sku", "location", "lot_serial_number"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("item_id", Type.IDENTIFIER, Req.RECOMMENDED, "Inventory item identifier."),
        nf("sku", Type.STRING, Req.REQUIRED, "Stock keeping unit.", nullable=False),
        nf("item_description", Type.STRING, Req.REQUIRED, "Inventory item description.", nullable=False),
        nf("category", Type.STRING, Req.OPTIONAL, "Inventory category."),
        nf("warehouse", Type.STRING, Req.RECOMMENDED, "Warehouse."),
        nf("location", Type.STRING, Req.REQUIRED, "Inventory location or bin.", nullable=False),
        nf("lot_serial_number", Type.STRING, Req.REQUIRED, "Lot or serial number; use 'NA' if not applicable.", nullable=False),
        nf("quantity_on_hand", Type.DECIMAL, Req.REQUIRED, "Book quantity on hand.", nullable=False),
        nf("uom", Type.STRING, Req.RECOMMENDED, "Unit of measure."),
        nf("unit_cost", Type.DECIMAL, Req.REQUIRED, "Unit cost.", nullable=False),
        nf("total_cost", Type.DECIMAL, Req.REQUIRED, "Quantity multiplied by unit cost.", nullable=False),
        nf(
            "valuation_method",
            Type.ENUM,
            Req.RECOMMENDED,
            "Inventory valuation method.",
            allowed_values=("fifo", "weighted_average", "standard_cost", "specific_identification"),
        ),
        nf("last_movement_date", Type.DATE, Req.OPTIONAL, "Last inventory movement date."),
        nf("obsolete_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether item is obsolete or slow moving."),
        nf("write_down_amount", Type.DECIMAL, Req.OPTIONAL, "Inventory write-down amount."),
        nf("physical_count_quantity", Type.DECIMAL, Req.OPTIONAL, "Physical count quantity."),
        nf("variance_quantity", Type.DECIMAL, Req.DERIVED, "Physical count less book quantity."),
        nf("variance_amount", Type.DECIMAL, Req.DERIVED, "Inventory count variance amount."),
        REMARKS,
    ),
    relationships=(
        rel(
            "inventory_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "Inventory listing total should roughly tie to inventory GL control account.",
            tolerance="Configured inventory summary difference pct.",
        ),
    ),
)

TAX_COMPUTATION_SCHEMA = DocumentSchema(
    document_type=DocumentType.TAX_COMPUTATION,
    display_name="Tax Computation",
    grain="One tax computation line or adjustment for the tax year.",
    primary_key=("client_id", "financial_year", "tax_year", "line_code"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("tax_year", Type.INTEGER, Req.REQUIRED, "Tax assessment year.", nullable=False),
        nf("tax_period", Type.STRING, Req.RECOMMENDED, "Tax computation period label."),
        nf("line_code", Type.STRING, Req.REQUIRED, "Tax computation line code.", nullable=False),
        nf("line_description", Type.STRING, Req.REQUIRED, "Tax computation line description.", nullable=False),
        nf("accounting_profit_before_tax", Type.DECIMAL, Req.OPTIONAL, "Accounting profit before tax."),
        nf(
            "tax_adjustment_type",
            Type.ENUM,
            Req.RECOMMENDED,
            "Tax adjustment category.",
            allowed_values=("addback", "deduction", "exemption", "tax_credit", "summary", "other"),
        ),
        nf("tax_adjustment_amount", Type.DECIMAL, Req.REQUIRED, "Tax adjustment or line amount.", nullable=False),
        nf("adjusted_income", Type.DECIMAL, Req.OPTIONAL, "Adjusted income after tax adjustments."),
        nf("capital_allowance", Type.DECIMAL, Req.OPTIONAL, "Capital allowance amount."),
        nf("unabsorbed_losses_brought_forward", Type.DECIMAL, Req.OPTIONAL, "Tax losses brought forward."),
        nf("chargeable_income", Type.DECIMAL, Req.OPTIONAL, "Chargeable income."),
        nf("tax_rate", Type.PERCENTAGE, Req.OPTIONAL, "Applicable tax rate."),
        nf("tax_payable", Type.DECIMAL, Req.OPTIONAL, "Tax payable."),
        nf("instalments_paid", Type.DECIMAL, Req.OPTIONAL, "Tax instalments paid."),
        nf("tax_balance", Type.DECIMAL, Req.OPTIONAL, "Tax payable or receivable balance."),
        REMARKS,
    ),
    relationships=(
        rel(
            "tax_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "Tax payable or receivable should roughly tie to tax accounts in the TB.",
            tolerance="Controlled by discrepancy settings.",
        ),
        rel(
            "tax_to_sst_gst",
            DocumentType.SST_GST_REPORT,
            "Indirect tax return totals may support selected tax computation lines.",
        ),
    ),
)

SST_GST_REPORT_SCHEMA = DocumentSchema(
    document_type=DocumentType.SST_GST_REPORT,
    display_name="SST/GST Report",
    grain="One indirect-tax transaction or return box line.",
    primary_key=("client_id", "financial_year", "reporting_period_end", "tax_line_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("tax_line_id", Type.IDENTIFIER, Req.REQUIRED, "Indirect tax line identifier.", nullable=False),
        nf("reporting_period_start", Type.DATE, Req.REQUIRED, "SST/GST reporting period start.", nullable=False),
        nf("reporting_period_end", Type.DATE, Req.REQUIRED, "SST/GST reporting period end.", nullable=False),
        nf("tax_type", Type.ENUM, Req.REQUIRED, "Tax regime.", allowed_values=("sst", "gst", "vat", "service_tax"), nullable=False),
        nf("tax_code", Type.STRING, Req.RECOMMENDED, "ERP tax code."),
        nf("transaction_date", Type.DATE, Req.OPTIONAL, "Transaction date."),
        nf("invoice_number", Type.STRING, Req.OPTIONAL, "Invoice or credit note number."),
        nf("counterparty_name", Type.STRING, Req.OPTIONAL, "Supplier or customer name."),
        nf("counterparty_tax_id", Type.STRING, Req.OPTIONAL, "Supplier or customer tax registration number."),
        nf("taxable_amount", Type.DECIMAL, Req.REQUIRED, "Taxable value before tax.", nullable=False),
        nf("tax_rate", Type.PERCENTAGE, Req.RECOMMENDED, "Tax rate."),
        nf("output_tax", Type.DECIMAL, Req.OPTIONAL, "Output tax amount."),
        nf("input_tax", Type.DECIMAL, Req.OPTIONAL, "Input tax amount."),
        nf("exempt_amount", Type.DECIMAL, Req.OPTIONAL, "Exempt supply amount."),
        nf("zero_rated_amount", Type.DECIMAL, Req.OPTIONAL, "Zero-rated supply amount."),
        nf("total_invoice_amount", Type.DECIMAL, Req.OPTIONAL, "Total invoice amount including tax."),
        nf("return_box", Type.STRING, Req.OPTIONAL, "Tax return box or field reference."),
        nf("source_module", Type.STRING, Req.OPTIONAL, "ERP source module."),
        REMARKS,
    ),
    relationships=(
        rel(
            "sst_gst_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Input and output tax should reconcile to GL tax accounts.",
            tolerance="Controlled by discrepancy settings.",
        ),
    ),
)

COMMISSION_STATEMENT_SCHEMA = DocumentSchema(
    document_type=DocumentType.COMMISSION_STATEMENT,
    display_name="Commission Statement",
    grain="One commission earning or clawback line.",
    primary_key=("client_id", "financial_year", "statement_id", "commission_line_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("statement_id", Type.IDENTIFIER, Req.REQUIRED, "Commission statement identifier.", nullable=False),
        nf("commission_line_id", Type.IDENTIFIER, Req.REQUIRED, "Commission line identifier.", nullable=False),
        nf("agent_id", Type.IDENTIFIER, Req.RECOMMENDED, "Agent or producer identifier."),
        nf("agent_name", Type.STRING, Req.REQUIRED, "Agent or producer name.", nullable=False),
        nf("sales_rep_id", Type.IDENTIFIER, Req.OPTIONAL, "Internal sales representative identifier."),
        nf("sales_rep_name", Type.STRING, Req.OPTIONAL, "Internal sales representative name."),
        nf("customer_id", Type.IDENTIFIER, Req.OPTIONAL, "Customer or insured identifier."),
        nf("customer_name", Type.STRING, Req.OPTIONAL, "Customer or insured name."),
        nf("policy_number", Type.STRING, Req.OPTIONAL, "Insurance policy number."),
        nf("invoice_number", Type.STRING, Req.OPTIONAL, "Invoice number."),
        nf("transaction_date", Type.DATE, Req.RECOMMENDED, "Commission transaction date."),
        nf("product_line", Type.STRING, Req.OPTIONAL, "Product or insurance class."),
        nf("gross_revenue", Type.DECIMAL, Req.REQUIRED, "Revenue or premium basis for commission.", nullable=False),
        nf("commission_rate", Type.PERCENTAGE, Req.RECOMMENDED, "Commission rate."),
        nf("commission_amount", Type.DECIMAL, Req.REQUIRED, "Gross commission amount.", nullable=False),
        nf("override_commission_amount", Type.DECIMAL, Req.OPTIONAL, "Override commission amount."),
        nf("clawback_amount", Type.DECIMAL, Req.OPTIONAL, "Commission clawback amount."),
        nf("net_commission", Type.DECIMAL, Req.REQUIRED, "Net commission after overrides and clawbacks.", nullable=False),
        nf("payment_status", Type.STRING, Req.RECOMMENDED, "Commission payment status."),
        nf("payment_date", Type.DATE, Req.OPTIONAL, "Commission payment date."),
        REMARKS,
    ),
    relationships=(
        rel(
            "commission_to_insurance_production",
            DocumentType.INSURANCE_PRODUCTION_REPORT,
            "Commission basis should link to production report policies or invoices.",
            join_fields=(("policy_number", "policy_number"),),
        ),
        rel(
            "commission_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Commission expense or income should be represented in GL postings.",
            tolerance="Controlled by discrepancy settings.",
        ),
    ),
)

INSURANCE_PRODUCTION_REPORT_SCHEMA = DocumentSchema(
    document_type=DocumentType.INSURANCE_PRODUCTION_REPORT,
    display_name="Insurance Production Report",
    grain="One insurance policy, endorsement, renewal, or cancellation production transaction.",
    primary_key=("client_id", "financial_year", "production_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("production_id", Type.IDENTIFIER, Req.REQUIRED, "Production transaction identifier.", nullable=False),
        nf("policy_number", Type.STRING, Req.REQUIRED, "Policy number.", nullable=False),
        nf("endorsement_number", Type.STRING, Req.OPTIONAL, "Endorsement number."),
        nf(
            "transaction_type",
            Type.ENUM,
            Req.REQUIRED,
            "Insurance production transaction type.",
            allowed_values=("new_business", "renewal", "endorsement", "cancellation", "reinstatement"),
            nullable=False,
        ),
        nf("effective_date", Type.DATE, Req.RECOMMENDED, "Policy effective date."),
        nf("expiry_date", Type.DATE, Req.RECOMMENDED, "Policy expiry date."),
        nf("issue_date", Type.DATE, Req.OPTIONAL, "Policy issue date."),
        nf("agent_id", Type.IDENTIFIER, Req.OPTIONAL, "Agent or broker identifier."),
        nf("agent_name", Type.STRING, Req.RECOMMENDED, "Agent or broker name."),
        nf("customer_id", Type.IDENTIFIER, Req.OPTIONAL, "Customer or insured identifier."),
        nf("customer_name", Type.STRING, Req.REQUIRED, "Customer or insured name.", nullable=False),
        nf("product_line", Type.STRING, Req.REQUIRED, "Insurance class or product line.", nullable=False),
        nf("gross_written_premium", Type.DECIMAL, Req.REQUIRED, "Gross written premium.", nullable=False),
        nf("net_written_premium", Type.DECIMAL, Req.RECOMMENDED, "Net written premium."),
        nf("sum_insured", Type.DECIMAL, Req.OPTIONAL, "Sum insured."),
        nf("commission_amount", Type.DECIMAL, Req.OPTIONAL, "Related commission amount."),
        nf("premium_tax", Type.DECIMAL, Req.OPTIONAL, "Premium tax or levy."),
        nf("fees", Type.DECIMAL, Req.OPTIONAL, "Policy fees."),
        nf("branch", Type.STRING, Req.OPTIONAL, "Branch or office."),
        nf("status", Type.STRING, Req.RECOMMENDED, "Policy transaction status."),
        REMARKS,
    ),
    relationships=(
        rel(
            "insurance_production_to_commission",
            DocumentType.COMMISSION_STATEMENT,
            "Production premium lines can drive commission calculations.",
            join_fields=(("policy_number", "policy_number"),),
        ),
        rel(
            "insurance_production_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Premium production should map to revenue, receivable, and tax GL entries.",
            tolerance="Controlled by discrepancy settings.",
        ),
    ),
)

CUSTOMER_CONFIRMATION_LIST_SCHEMA = DocumentSchema(
    document_type=DocumentType.CUSTOMER_CONFIRMATION_LIST,
    display_name="Customer Confirmation List",
    grain="One customer confirmation request and balance.",
    primary_key=("client_id", "financial_year", "period_end", "confirmation_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("confirmation_id", Type.IDENTIFIER, Req.REQUIRED, "Customer confirmation request identifier.", nullable=False),
        nf("customer_id", Type.IDENTIFIER, Req.REQUIRED, "Customer identifier.", nullable=False),
        nf("customer_name", Type.STRING, Req.REQUIRED, "Customer name.", nullable=False),
        nf("contact_name", Type.STRING, Req.OPTIONAL, "Customer contact name."),
        nf("contact_email", Type.STRING, Req.OPTIONAL, "Customer contact email."),
        nf("contact_address", Type.STRING, Req.OPTIONAL, "Customer mailing address."),
        nf("balance_date", Type.DATE, Req.REQUIRED, "Balance confirmation date.", nullable=False),
        nf("ar_balance", Type.DECIMAL, Req.REQUIRED, "AR balance selected for confirmation.", nullable=False),
        nf("invoice_count", Type.INTEGER, Req.OPTIONAL, "Number of invoices in the balance."),
        nf("sample_selected_flag", Type.BOOLEAN, Req.RECOMMENDED, "Whether selected for audit confirmation."),
        nf("confirmation_method", Type.STRING, Req.OPTIONAL, "Email, portal, mail, or phone."),
        nf("sent_date", Type.DATE, Req.OPTIONAL, "Confirmation sent date."),
        nf("response_date", Type.DATE, Req.OPTIONAL, "Confirmation response date."),
        nf("response_status", Type.STRING, Req.RECOMMENDED, "Response status."),
        nf("confirmed_amount", Type.DECIMAL, Req.OPTIONAL, "Amount confirmed by customer."),
        nf("difference_amount", Type.DECIMAL, Req.DERIVED, "Confirmed amount less AR balance."),
        nf("auditor_follow_up_required", Type.BOOLEAN, Req.OPTIONAL, "Whether follow-up is required."),
        REMARKS,
    ),
    relationships=(
        rel(
            "customer_confirmation_to_ar",
            DocumentType.AR_AGING,
            "Confirmation balances should trace to AR aging by customer.",
            join_fields=(("customer_id", "customer_id"),),
        ),
    ),
)

SUPPLIER_CONFIRMATION_LIST_SCHEMA = DocumentSchema(
    document_type=DocumentType.SUPPLIER_CONFIRMATION_LIST,
    display_name="Supplier Confirmation List",
    grain="One supplier confirmation request and balance.",
    primary_key=("client_id", "financial_year", "period_end", "confirmation_id"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("confirmation_id", Type.IDENTIFIER, Req.REQUIRED, "Supplier confirmation request identifier.", nullable=False),
        nf("vendor_id", Type.IDENTIFIER, Req.REQUIRED, "Supplier identifier.", nullable=False),
        nf("vendor_name", Type.STRING, Req.REQUIRED, "Supplier name.", nullable=False),
        nf("contact_name", Type.STRING, Req.OPTIONAL, "Supplier contact name."),
        nf("contact_email", Type.STRING, Req.OPTIONAL, "Supplier contact email."),
        nf("contact_address", Type.STRING, Req.OPTIONAL, "Supplier mailing address."),
        nf("balance_date", Type.DATE, Req.REQUIRED, "Balance confirmation date.", nullable=False),
        nf("ap_balance", Type.DECIMAL, Req.REQUIRED, "AP balance selected for confirmation.", nullable=False),
        nf("invoice_count", Type.INTEGER, Req.OPTIONAL, "Number of invoices in the balance."),
        nf("sample_selected_flag", Type.BOOLEAN, Req.RECOMMENDED, "Whether selected for audit confirmation."),
        nf("confirmation_method", Type.STRING, Req.OPTIONAL, "Email, portal, mail, or phone."),
        nf("sent_date", Type.DATE, Req.OPTIONAL, "Confirmation sent date."),
        nf("response_date", Type.DATE, Req.OPTIONAL, "Confirmation response date."),
        nf("response_status", Type.STRING, Req.RECOMMENDED, "Response status."),
        nf("confirmed_amount", Type.DECIMAL, Req.OPTIONAL, "Amount confirmed by supplier."),
        nf("difference_amount", Type.DECIMAL, Req.DERIVED, "Confirmed amount less AP balance."),
        nf("auditor_follow_up_required", Type.BOOLEAN, Req.OPTIONAL, "Whether follow-up is required."),
        REMARKS,
    ),
    relationships=(
        rel(
            "supplier_confirmation_to_ap",
            DocumentType.AP_AGING,
            "Confirmation balances should trace to AP aging by supplier.",
            join_fields=(("vendor_id", "vendor_id"),),
        ),
    ),
)

CASH_FLOW_SUMMARY_SCHEMA = DocumentSchema(
    document_type=DocumentType.CASH_FLOW_SUMMARY,
    display_name="Cash Flow Summary",
    grain="One cash flow line item for the reporting period.",
    primary_key=("client_id", "financial_year", "period_end", "line_code"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("line_code", Type.STRING, Req.REQUIRED, "Cash flow line code.", nullable=False),
        nf("line_description", Type.STRING, Req.REQUIRED, "Cash flow line description.", nullable=False),
        nf(
            "cash_flow_category",
            Type.ENUM,
            Req.REQUIRED,
            "Cash flow section.",
            allowed_values=("operating", "investing", "financing", "cash_reconciliation"),
            nullable=False,
        ),
        nf(
            "method",
            Type.ENUM,
            Req.RECOMMENDED,
            "Cash flow method.",
            allowed_values=("direct", "indirect", "mixed"),
        ),
        nf("amount_current_period", Type.DECIMAL, Req.REQUIRED, "Current period cash flow amount.", nullable=False),
        nf("amount_comparative_period", Type.DECIMAL, Req.OPTIONAL, "Comparative period amount."),
        nf("source_account_codes", Type.JSON, Req.OPTIONAL, "GL account codes supporting the line."),
        nf("subtotal_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether line is a subtotal or total."),
        nf("display_order", Type.INTEGER, Req.RECOMMENDED, "Presentation order."),
        REMARKS,
    ),
    relationships=(
        rel(
            "cash_flow_to_trial_balance",
            DocumentType.TRIAL_BALANCE,
            "Cash flow should be derivable from TB movement and cash account changes.",
            tolerance="Controlled by cash-flow assumptions.",
        ),
        rel(
            "cash_flow_to_bank_recon",
            DocumentType.BANK_RECONCILIATION,
            "Ending cash should align with reconciled cash balances.",
            tolerance="Configured bank reconciliation difference amount.",
        ),
    ),
)

JOURNAL_ENTRY_LISTING_SCHEMA = DocumentSchema(
    document_type=DocumentType.JOURNAL_ENTRY_LISTING,
    display_name="Journal Entry Listing",
    grain="One journal entry line with preparation and review metadata.",
    primary_key=("client_id", "financial_year", "journal_id", "line_number"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("journal_id", Type.IDENTIFIER, Req.REQUIRED, "Journal or voucher identifier.", nullable=False),
        nf("line_number", Type.INTEGER, Req.REQUIRED, "Line number in the journal.", nullable=False),
        nf("posting_date", Type.DATE, Req.REQUIRED, "Posting date.", nullable=False),
        nf("journal_date", Type.DATE, Req.OPTIONAL, "Journal creation or effective date."),
        nf("journal_type", Type.STRING, Req.RECOMMENDED, "Journal type."),
        nf("account_code", Type.STRING, Req.REQUIRED, "GL account code.", nullable=False),
        nf("account_name", Type.STRING, Req.RECOMMENDED, "GL account name."),
        nf("debit", Type.DECIMAL, Req.RECOMMENDED, "Debit amount."),
        nf("credit", Type.DECIMAL, Req.RECOMMENDED, "Credit amount."),
        nf("amount_signed", Type.DECIMAL, Req.REQUIRED, "Signed journal line amount.", nullable=False),
        nf("description", Type.STRING, Req.RECOMMENDED, "Journal line description."),
        nf("reference", Type.STRING, Req.OPTIONAL, "Voucher or supporting reference."),
        nf("prepared_by", Type.STRING, Req.OPTIONAL, "Journal preparer."),
        nf("approved_by", Type.STRING, Req.OPTIONAL, "Journal approver."),
        nf("approval_date", Type.DATE, Req.OPTIONAL, "Approval date."),
        nf("manual_entry_flag", Type.BOOLEAN, Req.RECOMMENDED, "Whether journal was manually prepared."),
        nf("recurring_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether journal is recurring."),
        nf("adjustment_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether journal is an adjustment."),
        nf("source_module", Type.STRING, Req.OPTIONAL, "ERP source module."),
        nf("cost_center", Type.STRING, Req.OPTIONAL, "Cost center."),
        nf("department", Type.STRING, Req.OPTIONAL, "Department."),
        REMARKS,
    ),
    relationships=(
        rel(
            "journal_entry_listing_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Journal entry listing should map to GL lines.",
            join_fields=(("journal_id", "journal_id"), ("line_number", "line_number")),
        ),
    ),
    quality_rules=("Each journal should balance debits and credits before configured chaos.",),
)

EXPENSE_CLAIM_LISTING_SCHEMA = DocumentSchema(
    document_type=DocumentType.EXPENSE_CLAIM_LISTING,
    display_name="Expense Claim Listing",
    grain="One employee expense claim line.",
    primary_key=("client_id", "financial_year", "claim_id", "line_number"),
    fields=COMMON_DOCUMENT_FIELDS
    + (
        nf("claim_id", Type.IDENTIFIER, Req.REQUIRED, "Expense claim identifier.", nullable=False),
        nf("line_number", Type.INTEGER, Req.REQUIRED, "Expense claim line number.", nullable=False),
        nf("employee_id", Type.IDENTIFIER, Req.REQUIRED, "Employee identifier.", nullable=False),
        nf("employee_name", Type.STRING, Req.REQUIRED, "Employee name.", nullable=False),
        nf("department", Type.STRING, Req.OPTIONAL, "Employee department."),
        nf("claim_date", Type.DATE, Req.REQUIRED, "Claim submission date.", nullable=False),
        nf("receipt_date", Type.DATE, Req.OPTIONAL, "Receipt date."),
        nf("expense_date", Type.DATE, Req.RECOMMENDED, "Expense transaction date."),
        nf("expense_category", Type.STRING, Req.REQUIRED, "Expense category.", nullable=False),
        nf("merchant", Type.STRING, Req.OPTIONAL, "Merchant or payee."),
        nf("description", Type.STRING, Req.RECOMMENDED, "Claim line description."),
        nf("amount_gross", Type.DECIMAL, Req.REQUIRED, "Gross claim amount.", nullable=False),
        nf("tax_amount", Type.DECIMAL, Req.OPTIONAL, "Tax amount included in claim."),
        nf("amount_net", Type.DECIMAL, Req.RECOMMENDED, "Net claim amount excluding tax."),
        nf("reimbursement_status", Type.STRING, Req.RECOMMENDED, "Reimbursement status."),
        nf("payment_date", Type.DATE, Req.OPTIONAL, "Payment date."),
        nf("approval_status", Type.STRING, Req.RECOMMENDED, "Approval status."),
        nf("approved_by", Type.STRING, Req.OPTIONAL, "Approver name."),
        nf("project_code", Type.STRING, Req.OPTIONAL, "Project code."),
        nf("cost_center", Type.STRING, Req.OPTIONAL, "Cost center."),
        nf("receipt_available_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether receipt is available."),
        nf("policy_exception_flag", Type.BOOLEAN, Req.OPTIONAL, "Whether claim violates policy."),
        REMARKS,
    ),
    relationships=(
        rel(
            "expense_claims_to_gl",
            DocumentType.GENERAL_LEDGER,
            "Approved and paid claims should map to expense and cash/AP GL entries.",
            tolerance="Controlled by discrepancy settings.",
        ),
        rel(
            "expense_claims_to_payroll",
            DocumentType.PAYROLL_DETAIL,
            "Some reimbursements may be paid through payroll and trace to employee IDs.",
            join_fields=(("employee_id", "employee_id"),),
        ),
    ),
)

ALL_DOCUMENT_SCHEMAS: tuple[DocumentSchema, ...] = (
    PBC_REQUEST_LIST_SCHEMA,
    TRIAL_BALANCE_SCHEMA,
    GENERAL_LEDGER_SCHEMA,
    AP_AGING_SCHEMA,
    AR_AGING_SCHEMA,
    BANK_RECONCILIATION_SCHEMA,
    PAYROLL_SUMMARY_SCHEMA,
    PAYROLL_DETAIL_SCHEMA,
    FIXED_ASSET_REGISTER_SCHEMA,
    INVENTORY_LISTING_SCHEMA,
    TAX_COMPUTATION_SCHEMA,
    SST_GST_REPORT_SCHEMA,
    COMMISSION_STATEMENT_SCHEMA,
    INSURANCE_PRODUCTION_REPORT_SCHEMA,
    CUSTOMER_CONFIRMATION_LIST_SCHEMA,
    SUPPLIER_CONFIRMATION_LIST_SCHEMA,
    CASH_FLOW_SUMMARY_SCHEMA,
    JOURNAL_ENTRY_LISTING_SCHEMA,
    EXPENSE_CLAIM_LISTING_SCHEMA,
)
