"""Structural workbook mutations for realistic PBC Excel layouts."""

from __future__ import annotations

from copy import copy
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from random import Random
import re
from typing import Any

from openpyxl import Workbook
from openpyxl.cell.cell import Cell
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

from pbc_chaos.reference_data.terms import COLUMN_ALIAS_FAMILIES


@dataclass(frozen=True)
class TableBounds:
    """Bounds for the primary table after layout mutations."""

    min_row: int
    min_col: int
    max_row: int
    max_col: int

    @property
    def header_row(self) -> int:
        return self.min_row

    @property
    def width(self) -> int:
        return self.max_col - self.min_col + 1


def find_used_range(worksheet: Worksheet) -> TableBounds | None:
    """Return the rectangular range containing non-empty cells."""

    used_rows: list[int] = []
    used_cols: list[int] = []
    for row in worksheet.iter_rows():
        for cell in row:
            if cell.value is not None:
                used_rows.append(cell.row)
                used_cols.append(cell.column)

    if not used_rows or not used_cols:
        return None
    return TableBounds(min(used_rows), min(used_cols), max(used_rows), max(used_cols))


def shift_table_away_from_a1(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    top_rows: int,
    left_columns: int,
) -> TableBounds:
    """Insert leading rows and columns so the table no longer begins at A1."""

    if top_rows > 0:
        worksheet.insert_rows(1, top_rows)
    if left_columns > 0:
        worksheet.insert_cols(1, left_columns)
    return TableBounds(
        table.min_row + top_rows,
        table.min_col + left_columns,
        table.max_row + top_rows,
        table.max_col + left_columns,
    )


def add_title_block(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    title: str,
    client_name: str,
    prepared_by: str,
    financial_year: int | None,
    rng: Random,
    merge_cells: bool = True,
    as_at: str | None = None,
    currency: str | None = None,
) -> TableBounds:
    """Add a finance-team style title and metadata block above the table."""

    insert_at = table.min_row
    worksheet.insert_rows(insert_at, 4)

    title_row = insert_at
    subtitle_row = insert_at + 1
    meta_row = insert_at + 2
    note_row = insert_at + 3
    min_col = table.min_col
    max_col = table.max_col

    if merge_cells:
        worksheet.merge_cells(
            start_row=title_row,
            start_column=min_col,
            end_row=title_row,
            end_column=max_col,
        )
    title_cell = worksheet.cell(title_row, min_col, title)
    title_cell.font = Font(bold=True, size=14, color="1F2937")
    title_cell.fill = PatternFill("solid", fgColor=rng.choice(["D9EAF7", "E2F0D9", "FFF2CC"]))
    title_cell.alignment = Alignment(horizontal="left")

    worksheet.cell(subtitle_row, min_col, f"Client: {client_name}")
    worksheet.cell(subtitle_row, min_col + 2, f"FY: {financial_year or 'per client file'}")
    if as_at:
        worksheet.cell(subtitle_row, min_col + 4, f"As at: {as_at}")
    worksheet.cell(meta_row, min_col, f"Prepared by: {prepared_by}")
    worksheet.cell(meta_row, min_col + 2, "Status: Draft for audit")
    if currency:
        worksheet.cell(meta_row, min_col + 4, f"All amounts in {currency}")
    worksheet.cell(note_row, min_col, "Please do not overwrite prior comments; audit team using this version.")

    return TableBounds(table.min_row + 4, table.min_col, table.max_row + 4, table.max_col)


def add_software_signature(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    signature: str,
    rng: Random,
) -> str:
    """Stamp an accounting-software export tag in the blank area above the table.

    Returns the text written so callers can record it in ground truth.
    """

    text = rng.choice(
        (
            f"Generated by {signature}",
            f"{signature} - System Generated Report",
            f"Exported from {signature}",
        )
    )
    target_row = max(1, table.min_row - 1)
    cell = worksheet.cell(target_row, table.min_col, text)
    cell.font = Font(italic=True, size=8, color="808080")
    return text


def add_report_footer_band(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    signature: str,
    prepared_by: str,
    reviewer_name: str,
    as_at: str | None,
) -> None:
    """Add a finance report footer band (sign-off + system + page) below the table."""

    start_row = table.max_row + 2
    lines = [
        f"Prepared by: {prepared_by}    Reviewed by: {reviewer_name}",
        f"System: {signature}" + (f"    Report date: {as_at}" if as_at else ""),
        "Page 1 of 1",
    ]
    for offset, text in enumerate(lines):
        cell = worksheet.cell(start_row + offset, table.min_col, text)
        cell.font = Font(italic=True, size=8, color="808080")


def add_client_notes(worksheet: Worksheet, table: TableBounds, *, rng: Random) -> TableBounds:
    """Add short client/audit notes above the table."""

    notes = [
        "Note: balances per GL export before late adjustments.",
        "Client comment: pending final AP accrual entries.",
        "Audit request: add support references where available.",
    ]
    insert_at = table.min_row
    worksheet.insert_rows(insert_at, 2)
    worksheet.cell(insert_at, table.min_col, rng.choice(notes))
    worksheet.cell(insert_at + 1, table.min_col, "Updated manually by finance after close meeting.")
    return TableBounds(table.min_row + 2, table.min_col, table.max_row + 2, table.max_col)


def insert_blank_rows_and_columns(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    row_count: int,
    column_count: int,
    rng: Random,
) -> TableBounds:
    """Insert blank separators in non-critical positions inside/near the table."""

    max_row = table.max_row
    max_col = table.max_col
    for _ in range(max(0, row_count)):
        if table.max_row - table.min_row < 3:
            break
        row_idx = rng.randint(table.min_row + 2, max_row)
        worksheet.insert_rows(row_idx, 1)
        max_row += 1

    for _ in range(max(0, column_count)):
        if table.max_col - table.min_col < 2:
            break
        col_idx = rng.randint(table.min_col + 1, max_col)
        worksheet.insert_cols(col_idx, 1)
        max_col += 1

    return TableBounds(table.min_row, table.min_col, max_row, max_col)


def duplicate_header_rows(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
) -> TableBounds:
    """Duplicate header rows where a user may have split a long table for viewing."""

    max_row = table.max_row
    for _ in range(max(0, count)):
        target = rng.randint(table.min_row + 3, max_row + 1)
        worksheet.insert_rows(target, 1)
        for col in range(table.min_col, table.max_col + 1):
            _copy_cell(worksheet.cell(table.header_row, col), worksheet.cell(target, col))
        max_row += 1
    return TableBounds(table.min_row, table.min_col, max_row, table.max_col)


def add_subtotal_rows(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
) -> TableBounds:
    """Insert subtotal rows with formulas under plausible table sections."""

    max_row = table.max_row
    numeric_cols = _numeric_columns(worksheet, table)
    for _ in range(max(0, count)):
        target = rng.randint(table.min_row + 4, max_row + 1)
        worksheet.insert_rows(target, 1)
        worksheet.cell(target, table.min_col, "Subtotal")
        worksheet.cell(target, table.min_col).font = Font(bold=True)
        for col in numeric_cols:
            letter = get_column_letter(col)
            start_row = max(table.min_row + 1, target - rng.randint(3, 8))
            worksheet.cell(target, col, f"=SUM({letter}{start_row}:{letter}{target - 1})")
            worksheet.cell(target, col).font = Font(bold=True)
        max_row += 1
    return TableBounds(table.min_row, table.min_col, max_row, table.max_col)


def add_footer_notes(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    rng: Random,
    merge_cells: bool = True,
) -> TableBounds:
    """Add footer notes below the table, with occasional in-table reminder text."""

    note_row = table.max_row + 2
    worksheet.cell(note_row, table.min_col, rng.choice([
        "Footer note: excludes intercompany eliminations not posted at extract date.",
        "Prepared from ERP export; manual reclasses highlighted by finance.",
        "Older review notes intentionally retained for audit trail.",
    ]))
    if merge_cells:
        worksheet.merge_cells(
            start_row=note_row,
            start_column=table.min_col,
            end_row=note_row,
            end_column=table.max_col,
        )
    worksheet.cell(note_row, table.min_col).font = Font(italic=True, color="666666")

    if table.max_row - table.min_row > 5:
        reminder_row = rng.randint(table.min_row + 2, table.max_row - 1)
        worksheet.cell(reminder_row, table.max_col, worksheet.cell(reminder_row, table.max_col).value)
        worksheet.cell(reminder_row, table.max_col).fill = PatternFill("solid", fgColor="FFF2CC")

    return table


def freeze_panes_near_table(worksheet: Worksheet, table: TableBounds) -> None:
    """Freeze panes just below/right of the primary header."""

    worksheet.freeze_panes = worksheet.cell(table.header_row + 1, table.min_col + 1).coordinate


def hide_random_rows_and_columns(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    row_count: int,
    column_count: int,
    rng: Random,
) -> None:
    """Hide non-header rows and non-key columns to mimic manual working files."""

    candidate_rows = list(range(table.min_row + 2, table.max_row + 1))
    rng.shuffle(candidate_rows)
    for row in candidate_rows[: max(0, row_count)]:
        worksheet.row_dimensions[row].hidden = True

    candidate_cols = list(range(table.min_col + 1, table.max_col + 1))
    rng.shuffle(candidate_cols)
    for col in candidate_cols[: max(0, column_count)]:
        worksheet.column_dimensions[get_column_letter(col)].hidden = True


def add_old_version_tabs(
    workbook: Workbook,
    *,
    source: Worksheet,
    count: int,
    rng: Random,
) -> list[str]:
    """Copy the active worksheet into visible old-version tabs."""

    sheet_names: list[str] = []
    for idx in range(1, max(0, count) + 1):
        copied = workbook.copy_worksheet(source)
        copied.title = _safe_sheet_title(workbook, f"{source.title}_old_v{idx}")
        copied.sheet_properties.tabColor = rng.choice(["C9C9C9", "F4B183", "BDD7EE"])
        copied["A1"] = "OLD VERSION - retained for support trail"
        sheet_names.append(copied.title)
    return sheet_names


def add_hidden_reconciliation_tab(workbook: Workbook, *, source: Worksheet) -> Worksheet:
    """Create a hidden working tab that looks like a client reconciliation scratchpad."""

    title = _safe_sheet_title(workbook, "_recon_working")
    sheet = workbook.create_sheet(title)
    sheet.sheet_state = "hidden"
    rows: tuple[tuple[Any, ...], ...] = (
        ("Source sheet", source.title),
        ("Check", "Amount per support"),
        ("GL total", None),
        ("PBC total", None),
        ("Variance", "=B3-B4"),
        ("Prepared by", "Client finance"),
    )
    for row in rows:
        sheet.append(row)
    sheet["A1"].font = Font(bold=True)
    return sheet


def rename_random_columns(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
    sheet_name: str | None = None,
) -> dict[str, str]:
    """Rename selected headers using common finance shorthand."""

    candidates = []
    for col in range(table.min_col, table.max_col + 1):
        value = worksheet.cell(table.header_row, col).value
        if value is not None:
            candidates.append((col, str(value)))
    rng.shuffle(candidates)

    used_headers = {_normalize_header_key(header) for _, header in candidates}
    mapping: dict[str, str] = {}
    for col, header in candidates[: max(0, count)]:
        choices = _column_alias_choices(header, sheet_name=sheet_name)
        renamed = _choose_distinct_alias(header, choices, used_headers, rng)
        worksheet.cell(table.header_row, col).value = renamed
        used_headers.discard(_normalize_header_key(header))
        used_headers.add(_normalize_header_key(renamed))
        mapping[header] = renamed
    return mapping


def stringify_numeric_cells(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
) -> list[dict[str, Any]]:
    """Convert selected numeric cells to text while preserving the visible value."""

    candidates = [
        cell
        for row in worksheet.iter_rows(
            min_row=table.min_row + 1,
            max_row=table.max_row,
            min_col=table.min_col,
            max_col=table.max_col,
        )
        for cell in row
        if isinstance(cell.value, int | float) and not isinstance(cell.value, bool)
    ]
    rng.shuffle(candidates)
    changed: list[dict[str, Any]] = []
    for cell in candidates[: max(0, count)]:
        original = cell.value
        cell.value = f"{float(cell.value):,.2f}"
        changed.append(
            {
                "cell": cell.coordinate,
                "original_value": original,
                "new_value": cell.value,
            }
        )
    return changed


def inject_formula_errors(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
) -> list[dict[str, Any]]:
    """Replace a few numeric cells with broken formulas."""

    candidates = [
        cell
        for row in worksheet.iter_rows(
            min_row=table.min_row + 1,
            max_row=table.max_row,
            min_col=table.min_col,
            max_col=table.max_col,
        )
        for cell in row
        if isinstance(cell.value, int | float) and not isinstance(cell.value, bool)
    ]
    rng.shuffle(candidates)
    errors = ("=#REF!", "=SUM(#REF!)", "=1/0")
    changed: list[dict[str, Any]] = []
    for cell in candidates[: max(0, count)]:
        original = cell.value
        cell.value = rng.choice(errors)
        changed.append(
            {
                "cell": cell.coordinate,
                "original_value": original,
                "new_value": cell.value,
            }
        )
    return changed


def insert_wrong_period_rows(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
) -> tuple[TableBounds, list[dict[str, Any]]]:
    """Copy rows and move date/year values outside the reporting period."""

    date_columns = _date_like_columns(worksheet, table)
    if not date_columns or table.max_row <= table.min_row:
        return table, []

    max_row = table.max_row
    inserted: list[dict[str, Any]] = []
    for _ in range(max(0, count)):
        source_row = rng.randint(table.min_row + 1, max_row)
        target_row = source_row + 1
        worksheet.insert_rows(target_row, 1)
        for col in range(table.min_col, table.max_col + 1):
            _copy_cell(worksheet.cell(source_row, col), worksheet.cell(target_row, col))
        changed_cells = []
        for col in date_columns:
            cell = worksheet.cell(target_row, col)
            original = cell.value
            cell.value = _wrong_period_value(cell.value)
            cell.fill = PatternFill("solid", fgColor="F8CBAD")
            changed_cells.append(
                {
                    "cell": cell.coordinate,
                    "original_value": original,
                    "new_value": cell.value,
                }
            )
        worksheet.cell(target_row, table.min_col).font = Font(italic=True, color="C00000")
        inserted.append(
            {
                "source_row": source_row,
                "inserted_row": target_row,
                "changed_cells": changed_cells,
            }
        )
        max_row += 1
    return TableBounds(table.min_row, table.min_col, max_row, table.max_col), inserted


def add_secondary_tables(
    worksheet: Worksheet,
    table: TableBounds,
    *,
    count: int,
    rng: Random,
) -> list[dict[str, Any]]:
    """Add small side tables below the main table."""

    tables: list[dict[str, Any]] = []
    for index in range(max(0, count)):
        start_row = table.max_row + 4 + index * 6
        start_col = table.min_col + rng.randint(0, min(2, max(0, table.width - 3)))
        worksheet.cell(start_row, start_col, rng.choice(["Manual recon", "Finance notes", "Late adjustments"]))
        worksheet.cell(start_row, start_col).font = Font(bold=True)
        headers = ("Ref", "Description", "Amount")
        for offset, header in enumerate(headers):
            cell = worksheet.cell(start_row + 1, start_col + offset, header)
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill("solid", fgColor="7F7F7F")
        for row_offset in range(2, 5):
            worksheet.cell(start_row + row_offset, start_col, f"M-{index + 1}-{row_offset - 1}")
            worksheet.cell(
                start_row + row_offset,
                start_col + 1,
                rng.choice(["Accrual true-up", "Timing item", "Client estimate"]),
            )
            worksheet.cell(start_row + row_offset, start_col + 2, round(rng.uniform(-5000, 5000), 2))
        tables.append(
            {
                "name": worksheet.cell(start_row, start_col).value,
                "start_cell": worksheet.cell(start_row, start_col).coordinate,
                "end_cell": worksheet.cell(start_row + 4, start_col + 2).coordinate,
            }
        )
    return tables


def _numeric_columns(worksheet: Worksheet, table: TableBounds) -> list[int]:
    columns: list[int] = []
    for col in range(table.min_col, table.max_col + 1):
        numeric_cells = 0
        for row in range(table.min_row + 1, min(table.max_row, table.min_row + 10) + 1):
            if isinstance(worksheet.cell(row, col).value, int | float):
                numeric_cells += 1
        if numeric_cells >= 2:
            columns.append(col)
    return columns


def _date_like_columns(worksheet: Worksheet, table: TableBounds) -> list[int]:
    columns: list[int] = []
    for col in range(table.min_col, table.max_col + 1):
        header = str(worksheet.cell(table.header_row, col).value or "").lower()
        if any(token in header for token in ("date", "period", "year", "fy")):
            columns.append(col)
            continue
        for row in range(table.min_row + 1, min(table.max_row, table.min_row + 10) + 1):
            value = worksheet.cell(row, col).value
            if isinstance(value, date | datetime):
                columns.append(col)
                break
    return columns


def _wrong_period_value(value: Any) -> Any:
    if isinstance(value, datetime):
        return value + timedelta(days=370)
    if isinstance(value, date):
        return value + timedelta(days=370)
    if isinstance(value, int) and 1900 <= value <= 2200:
        return value + 1
    if isinstance(value, str):
        stripped = value.strip()
        if len(stripped) >= 4 and stripped[:4].isdigit():
            return f"{int(stripped[:4]) + 1}{stripped[4:]}"
    return value


def _column_alias_choices(header: str, *, sheet_name: str | None) -> tuple[str, ...]:
    key = _normalize_header_key(header)
    choices = (
        COLUMN_ALIAS_FAMILIES.get(key, ())
        + _generated_header_aliases(header)
        + _sheet_context_aliases(key, sheet_name)
    )
    return tuple(dict.fromkeys(choices))


def _choose_distinct_alias(
    header: str,
    choices: tuple[str, ...],
    used_headers: set[str],
    rng: Random,
) -> str:
    original_key = _normalize_header_key(header)
    normalized_seen: set[str] = set()
    distinct_choices: list[str] = []
    for choice in choices:
        value = str(choice).strip()
        if not value:
            continue
        choice_key = _normalize_header_key(value)
        if choice_key == original_key or choice_key in normalized_seen:
            continue
        normalized_seen.add(choice_key)
        distinct_choices.append(value)

    unused_choices = [
        choice
        for choice in distinct_choices
        if _normalize_header_key(choice) not in used_headers
    ]
    pool = unused_choices or distinct_choices
    if pool:
        return rng.choice(pool)
    return _humanize_header(header)


def _generated_header_aliases(header: str) -> tuple[str, ...]:
    words = _header_words(header)
    if not words:
        return (header,)

    title_words = tuple(word.title() for word in words)
    abbreviated_words = tuple(_abbreviate_header_word(word) for word in words)
    return (
        " ".join(title_words),
        "".join(title_words),
        " ".join(abbreviated_words),
        " ".join(word.upper() for word in abbreviated_words),
        "-".join(title_words),
    )


def _sheet_context_aliases(key: str, sheet_name: str | None) -> tuple[str, ...]:
    acronym = _sheet_acronym(sheet_name)
    if not acronym:
        return ()

    if key == "account_code":
        if acronym == "GL":
            return ("GL Account", "GL Account No", "Ledger Account")
        return (f"{acronym} Account", f"{acronym} Acct Code")
    if key == "account_name":
        return (f"{acronym} Description", f"{acronym} Account Name")
    if key in {
        "amount_signed",
        "closing_balance",
        "current_amount",
        "difference_amount",
        "outstanding_amount",
        "original_amount",
    }:
        return (f"{acronym} Amount", f"{acronym} Bal")
    return ()


def _sheet_acronym(sheet_name: str | None) -> str:
    if not sheet_name:
        return ""
    words = _header_words(sheet_name)
    if not words:
        return ""
    return "".join(word[0].upper() for word in words[:3])


def _header_words(value: str) -> tuple[str, ...]:
    return tuple(match.group(0).lower() for match in re.finditer(r"[A-Za-z0-9]+", value))


def _normalize_header_key(value: str) -> str:
    return "_".join(_header_words(value))


def _abbreviate_header_word(word: str) -> str:
    abbreviations = {
        "account": "Acct",
        "amount": "Amt",
        "balance": "Bal",
        "category": "Cat",
        "center": "Ctr",
        "centre": "Ctr",
        "closing": "Close",
        "comparative": "Comp",
        "credit": "Cr",
        "customer": "Cust",
        "debit": "Dr",
        "department": "Dept",
        "description": "Desc",
        "document": "Doc",
        "financial": "Fin",
        "invoice": "Inv",
        "number": "No",
        "opening": "Open",
        "outstanding": "OS",
        "period": "Pd",
        "posting": "Post",
        "reference": "Ref",
        "transaction": "Txn",
        "vendor": "Vend",
        "year": "Yr",
    }
    return abbreviations.get(word, word.title())


def _humanize_header(header: str) -> str:
    words = header.replace("_", " ").split()
    if not words:
        return header
    return " ".join(word[:4].title() if len(word) > 4 else word.title() for word in words)


def _copy_cell(source: Cell, target: Cell) -> None:
    target.value = source.value
    if source.has_style:
        target.font = copy(source.font)
        target.fill = copy(source.fill)
        target.border = copy(source.border)
        target.alignment = copy(source.alignment)
        target.number_format = source.number_format
        target.protection = copy(source.protection)


def _safe_sheet_title(workbook: Workbook, title: str) -> str:
    base = title[:31]
    candidate = base
    suffix = 1
    while candidate in workbook.sheetnames:
        suffix_text = f"_{suffix}"
        candidate = f"{base[: 31 - len(suffix_text)]}{suffix_text}"
        suffix += 1
    return candidate
