"""Reusable terminology families for semantic chaos."""

COLUMN_ALIAS_FAMILIES: dict[str, tuple[str, ...]] = {
    "client_id": (
        "Client ID",
        "Client No",
        "Entity ID",
        "Co ID",
        "Company Code",
        "Client Ref",
    ),
    "client_name": (
        "Client",
        "Client Name",
        "Company",
        "Company Name",
        "Co Name",
        "Entity",
        "Entity Name",
    ),
    "financial_year": (
        "FY",
        "FYE",
        "Fin Year",
        "Financial Yr",
        "Year",
        "Audit Year",
        "Reporting Year",
    ),
    "period_start": (
        "From",
        "Start Date",
        "Period From",
        "Opening Date",
        "Start",
        "Date From",
    ),
    "period_end": (
        "To",
        "As At",
        "As at Date",
        "Period End",
        "End Date",
        "Balance Date",
        "Date To",
    ),
    "currency": (
        "Currency",
        "CCY",
        "Curr",
        "Currency Code",
        "Local CCY",
        "Rpt CCY",
    ),
    "account_code": (
        "GL",
        "GL Code",
        "GL No",
        "GL #",
        "Ledger",
        "Ledger Code",
        "Ledger No",
        "Acc Code",
        "Acc. Code",
        "Acct Code",
        "Acct No",
        "Acct #",
        "A/C",
        "A/C No",
        "Account No",
        "Account Number",
        "Account ID",
        "Account Code",
        "Nominal Code",
        "COA",
        "COA Code",
        "Chart Code",
        "ERP Account",
        "ERP Acct",
        "Main Account",
    ),
    "account_name": (
        "Account",
        "Account Name",
        "Account Description",
        "Acct Name",
        "Acct Desc",
        "Description",
        "GL Description",
        "Ledger Desc",
        "Ledger Name",
        "Nominal Name",
        "COA Name",
        "Account Title",
        "Particulars",
    ),
    "account_category": (
        "Category",
        "Acct Category",
        "FS Category",
        "Financial Category",
        "Type",
        "Account Type",
        "Class",
    ),
    "normal_balance": (
        "Normal Bal",
        "Natural Balance",
        "Dr/Cr",
        "Balance Type",
        "Debit Credit",
    ),
    "opening_debit": (
        "Opening Dr",
        "Open Debit",
        "Beg Dr",
        "B/F Dr",
        "Debit B/F",
    ),
    "opening_credit": (
        "Opening Cr",
        "Open Credit",
        "Beg Cr",
        "B/F Cr",
        "Credit B/F",
    ),
    "period_debit": (
        "Period Dr",
        "Debit Movement",
        "Movement Dr",
        "Current Dr",
        "YTD Dr",
    ),
    "period_credit": (
        "Period Cr",
        "Credit Movement",
        "Movement Cr",
        "Current Cr",
        "YTD Cr",
    ),
    "closing_debit": (
        "Closing Dr",
        "Close Debit",
        "Ending Dr",
        "Debit C/F",
        "Final Dr",
    ),
    "closing_credit": (
        "Closing Cr",
        "Close Credit",
        "Ending Cr",
        "Credit C/F",
        "Final Cr",
    ),
    "closing_balance": (
        "Closing Bal",
        "Closing Balance",
        "Balance",
        "Bal",
        "Amount",
        "Amt",
        "FY Bal",
        "Year End Bal",
        "Final Amount",
        "Signed Balance",
        "RM",
        "MYR",
        "Value",
        "Net Balance",
    ),
    "comparative_balance": (
        "Comparative",
        "PY Balance",
        "Prior Year",
        "Last Year Bal",
        "2024 Bal",
        "Prev Year",
    ),
    "adjustment_amount": (
        "Adjustment",
        "Adj",
        "Audit Adj",
        "Manual Adj",
        "Reclass",
        "Proposed Adj",
    ),
    "final_balance": (
        "Final Bal",
        "Final Balance",
        "After Adj",
        "Adjusted Balance",
        "Adjusted Bal",
        "Audit Final",
    ),
    "entry_id": (
        "Entry ID",
        "GL Entry",
        "Line ID",
        "Posting ID",
        "Txn ID",
        "Transaction ID",
    ),
    "journal_id": (
        "Journal",
        "Journal No",
        "JRN No",
        "JV No",
        "Voucher",
        "Voucher No",
        "Batch Journal",
    ),
    "line_number": (
        "Line",
        "Line No",
        "Ln",
        "Item",
        "Seq",
        "Sequence",
    ),
    "posting_date": (
        "Posting Date",
        "Post Dt",
        "GL Date",
        "Entry Date",
        "Posted On",
        "Transaction Date",
        "Txn Date",
    ),
    "document_date": (
        "Doc Date",
        "Document Date",
        "Invoice Date",
        "Source Date",
        "Ref Date",
    ),
    "period": (
        "Period",
        "Month",
        "Acct Period",
        "Posting Period",
        "YYYY-MM",
    ),
    "debit": (
        "Debit",
        "Dr",
        "Debit Amt",
        "Debit Amount",
        "DR Amount",
        "Debit RM",
    ),
    "credit": (
        "Credit",
        "Cr",
        "Credit Amt",
        "Credit Amount",
        "CR Amount",
        "Credit RM",
    ),
    "amount_signed": (
        "Signed Amt",
        "Signed Amount",
        "Net Amt",
        "Net Amount",
        "Amount",
        "Txn Amount",
        "Line Amount",
    ),
    "counterparty_id": (
        "Party ID",
        "Counterparty ID",
        "Vendor/Customer ID",
        "Subledger ID",
        "Name Code",
    ),
    "counterparty_name": (
        "Counterparty",
        "Party Name",
        "Vendor/Customer",
        "Name",
        "Subledger Name",
    ),
    "counterparty_type": (
        "Party Type",
        "Counterparty Type",
        "Subledger Type",
        "Customer/Supplier",
    ),
    "source_module": (
        "Module",
        "Source Module",
        "ERP Module",
        "Source",
        "System Source",
    ),
    "document_number": (
        "Doc No",
        "Document No",
        "Invoice/Doc No",
        "Source Doc",
        "Ref Doc No",
    ),
    "reference": (
        "Ref",
        "Reference",
        "Ref No",
        "Cheque/Ref",
        "External Ref",
        "Support Ref",
    ),
    "description": (
        "Description",
        "Desc",
        "Narration",
        "Particulars",
        "Details",
        "Transaction Details",
    ),
    "cost_center": (
        "Cost Center",
        "Cost Centre",
        "CC",
        "Cost Ctr",
        "Dept Code",
    ),
    "department": (
        "Department",
        "Dept",
        "Division",
        "Business Unit",
        "BU",
    ),
    "project_code": (
        "Project",
        "Project Code",
        "Job Code",
        "Job",
        "PRJ",
    ),
    "tax_code": (
        "Tax Code",
        "SST Code",
        "GST Code",
        "Tax",
        "Output/Input Tax",
    ),
    "created_by": (
        "Created By",
        "Input By",
        "Prepared By",
        "User",
        "Maker",
    ),
    "posted_by": (
        "Posted By",
        "Approved By",
        "Poster",
        "Posted User",
        "Checker",
    ),
    "batch_id": (
        "Batch",
        "Batch ID",
        "Batch No",
        "Upload Batch",
        "Import Batch",
    ),
    "reversal_flag": (
        "Reversal",
        "Reverse Flag",
        "Reversed?",
        "Rev",
        "Reversal Ind",
    ),
    "vendor_id": (
        "Vendor ID",
        "Supplier ID",
        "Supplier Code",
        "Creditor Code",
        "Payee Code",
    ),
    "vendor_name": (
        "Vendor",
        "Vendor Name",
        "Supplier",
        "Supplier Name",
        "Creditor",
        "Payee",
    ),
    "customer_id": (
        "Customer ID",
        "Customer Code",
        "Debtor Code",
        "Cust No",
        "Debtor ID",
    ),
    "customer_name": (
        "Customer",
        "Customer Name",
        "Debtor",
        "Debtor Name",
        "Client Customer",
        "Bill To",
    ),
    "invoice_number": (
        "Invoice",
        "Invoice No",
        "Inv No",
        "Inv #",
        "Bill No",
        "Doc No",
    ),
    "invoice_date": (
        "Invoice Date",
        "Inv Date",
        "Bill Date",
        "Doc Date",
        "Invoice Dt",
    ),
    "due_date": (
        "Due Date",
        "Due Dt",
        "Payment Due",
        "Collection Due",
        "Maturity Date",
    ),
    "aging_date": (
        "Aging Date",
        "Ageing Date",
        "As At",
        "Report Date",
        "Cutoff Date",
    ),
    "days_past_due": (
        "Days Due",
        "DPD",
        "Days OD",
        "Overdue Days",
        "Age Days",
    ),
    "aging_bucket": (
        "Aging Bucket",
        "Ageing",
        "Bucket",
        "Age Band",
        "Aging Band",
    ),
    "original_amount": (
        "Original Amt",
        "Original Amount",
        "Invoice Amount",
        "Inv Amt",
        "Gross Amt",
    ),
    "outstanding_amount": (
        "Outstanding",
        "Outstanding Amt",
        "Open Amt",
        "Open Amount",
        "Balance Due",
        "Unpaid Amount",
        "O/S",
    ),
    "current_amount": (
        "Current",
        "Current Amt",
        "Not Due",
        "0-Current",
        "Current Bucket",
    ),
    "bucket_1_30": (
        "1-30",
        "1 to 30",
        "30 Days",
        "0-30",
        "1_30",
    ),
    "bucket_31_60": (
        "31-60",
        "31 to 60",
        "60 Days",
        "31_60",
    ),
    "bucket_61_90": (
        "61-90",
        "61 to 90",
        "90 Days",
        "61_90",
    ),
    "bucket_over_90": (
        ">90",
        "Over 90",
        "90+",
        "Above 90",
        "Overdue 90+",
    ),
    "remarks": (
        "Remarks",
        "Remark",
        "Notes",
        "Comments",
        "Review Notes",
        "Finance Notes",
        "Audit Notes",
    ),
}

ACCOUNT_COLUMN_ALIASES = COLUMN_ALIAS_FAMILIES["account_code"]

AMOUNT_COLUMN_ALIASES = tuple(
    dict.fromkeys(
        COLUMN_ALIAS_FAMILIES["closing_balance"]
        + COLUMN_ALIAS_FAMILIES["amount_signed"]
        + COLUMN_ALIAS_FAMILIES["outstanding_amount"]
    )
)

HUMAN_RESIDUE_PHRASES = (
    "pls ignore old version",
    "FINAL FINAL v2",
    "updated after Jason review",
    "pending client confirmation",
    "not tally",
    "revised based on audit query",
)
